import sys

new_en_keys = """
      'monthly_reports_heading': 'Monthly Reports',
      'monthly_reports_sub': 'Paid amounts use the payment date. Other requests use their submission date.',
      'prev_month': 'Previous month',
      'next_month': 'Next month',
      'requester': 'Requester',
      'all_users_dd': 'All users',
      'status': 'Status',
      'all_statuses_dd': 'All statuses',
      'data_outdated': 'Data could not be refreshed. Displayed values may be out of date.',
      'total_paid': 'Total paid',
      'vs_prev_month': '% vs previous month',
      'no_prev_paid': 'No previous paid amount',
      'requests_in_view': 'Requests in view',
      'all_filters_applied': 'All active filters applied',
      'pending': 'Pending',
      'awaiting_decision': 'Awaiting a decision',
      'rejected': 'Rejected',
      'review_reasons': 'Review reasons in request details',
      'historical_payments_no_date': ' historical payment(s) have no verified payment date and are excluded from monthly totals.',
      'request_details': 'Request details',
      'no_requests_match': 'No requests match these filters.',
      'id_date': 'ID / Date',
      'description_th': 'Description',
      'amount_th': 'Amount',
      'status_th': 'Status',
      'page': 'Page',
      'of': 'of',
      'requests_suffix': 'requests',
      'financial_analytics_reports': 'Financial Analytics & Reports',
      'financial_analytics_sub': 'Real-time overview of petty cash outflows, approvals, and queue bottlenecks',
      'total_disbursed': 'TOTAL DISBURSED',
      'approved_payments_suffix': ' approved payments',
      'pending_queue': 'PENDING QUEUE',
      'requests_awaiting_review': ' requests awaiting review',
      'approval_rate': 'APPROVAL RATE',
      'of_reviewed': ' of reviewed',
      'rejection_count': 'REJECTION COUNT',
      'returned_to_requester': 'Returned to requester',
      'req_status_dist': 'Request Status Distribution',
      'req_status_dist_sub': 'Proportion of approved, pending, and rejected requests',
      'no_req_data': 'No request data available',
      'recent_exp_amt_comp': 'Recent Expense Amount Comparison',
      'recent_exp_amt_sub': 'Amounts of the latest expense submissions (Rs)',
      'no_transactions_recorded_yet': 'No transactions recorded yet.',
      'disbursements_by_req': 'Disbursements by Requester',
      'disbursements_by_req_sub': 'Actual paid expenditure per staff member',
      'no_paid_transactions_yet': 'No paid transactions found yet.',
      'org_financial_control': 'Organizational Financial Control',
"""

new_ur_keys = """
      'monthly_reports_heading': 'ماہانہ رپورٹس',
      'monthly_reports_sub': 'ادائیگی کی تاریخ استعمال کی جاتی ہے۔ دوسری درخواستوں کے لیے جمع کرانے کی تاریخ۔',
      'prev_month': 'پچھلا مہینہ',
      'next_month': 'اگلا مہینہ',
      'requester': 'درخواست دہندہ',
      'all_users_dd': 'تمام صارفین',
      'status': 'اسٹیٹس',
      'all_statuses_dd': 'تمام اسٹیٹس',
      'data_outdated': 'ڈیٹا ریفریش نہیں ہو سکا۔ اقدار پرانی ہو سکتی ہیں۔',
      'total_paid': 'کل ادائیگی',
      'vs_prev_month': '% بمقابلہ پچھلا مہینہ',
      'no_prev_paid': 'کوئی پچھلی ادائیگی نہیں',
      'requests_in_view': 'درخواستیں پیش نظر',
      'all_filters_applied': 'تمام فلٹرز لاگو ہیں',
      'pending': 'زیر التواء',
      'awaiting_decision': 'فیصلے کے منتظر',
      'rejected': 'مسترد شدہ',
      'review_reasons': 'درخواست کی تفصیلات میں وجوہات کا جائزہ لیں',
      'historical_payments_no_date': ' تاریخی ادائیگیوں کی تاریخ نہیں ہے اور انہیں ماہانہ حسابات سے نکال دیا گیا ہے۔',
      'request_details': 'درخواست کی تفصیلات',
      'no_requests_match': 'ان فلٹرز سے کوئی درخواست مماثل نہیں ہے۔',
      'id_date': 'آئی ڈی / تاریخ',
      'description_th': 'تفصیل',
      'amount_th': 'رقم',
      'status_th': 'اسٹیٹس',
      'page': 'صفحہ',
      'of': 'از',
      'requests_suffix': 'درخواستیں',
      'financial_analytics_reports': 'مالیاتی تجزیات اور رپورٹس',
      'financial_analytics_sub': 'پیٹی کیش، منظوریوں، اور قطار کے مسائل کا ریئل ٹائم جائزہ',
      'total_disbursed': 'کل جاری کردہ',
      'approved_payments_suffix': ' منظور شدہ ادائیگیاں',
      'pending_queue': 'زیر التواء قطار',
      'requests_awaiting_review': ' جائزے کے منتظر',
      'approval_rate': 'منظوری کی شرح',
      'of_reviewed': ' جائزوں میں سے',
      'rejection_count': 'مسترد ہونے کی تعداد',
      'returned_to_requester': 'درخواست دہندہ کو واپس کر دی گئی',
      'req_status_dist': 'درخواستوں کی تقسیم',
      'req_status_dist_sub': 'منظور شدہ، زیر التواء، اور مسترد شدہ کا تناسب',
      'no_req_data': 'کوئی ڈیٹا دستیاب نہیں',
      'recent_exp_amt_comp': 'حالیہ اخراجات کا موازنہ',
      'recent_exp_amt_sub': 'تازہ ترین جمع کرائے گئے اخراجات کی رقم',
      'no_transactions_recorded_yet': 'ابھی تک کوئی لین دین ریکارڈ نہیں ہوا۔',
      'disbursements_by_req': 'درخواست گزار کے لحاظ سے اخراجات',
      'disbursements_by_req_sub': 'ہر عملے کے ممبر کے لیے ادا شدہ اخراجات',
      'no_paid_transactions_yet': 'ابھی تک کوئی ادا شدہ لین دین نہیں ملا۔',
      'org_financial_control': 'تنظیمی مالی کنٹرول',
"""

with open('lib/l10n/translations.dart', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace(
    "'remove_user_tooltip': 'Remove User',",
    "'remove_user_tooltip': 'Remove User',\n" + new_en_keys
)

content = content.replace(
    "'remove_user_tooltip': 'صارف کو ہٹائیں',",
    "'remove_user_tooltip': 'صارف کو ہٹائیں',\n" + new_ur_keys
)

with open('lib/l10n/translations.dart', 'w', encoding='utf-8') as f:
    f.write(content)
print("Keys added to translations.dart")
