BEGIN;

-- New payment flows are additive. Historical public.requests rows remain untouched.
CREATE TABLE IF NOT EXISTS public.advances (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 given_by uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 amount numeric(12,2) NOT NULL CHECK (amount > 0 AND amount::text NOT IN ('NaN','Infinity','-Infinity')),
 finance_method text NOT NULL CHECK (finance_method IN ('Cash','Card')),
 received_method text CHECK (received_method IN ('Cash','Card')),
 status text NOT NULL DEFAULT 'Awaiting Confirmation' CHECK (status IN ('Awaiting Confirmation','Received')),
 mismatch_flag boolean NOT NULL DEFAULT false,
 note text CHECK (length(note) <= 2000),
 created_at timestamptz NOT NULL DEFAULT now(),
 confirmed_at timestamptz,
 CONSTRAINT advance_confirmation_consistent CHECK (
  (status='Awaiting Confirmation' AND received_method IS NULL AND confirmed_at IS NULL AND NOT mismatch_flag)
  OR (status='Received' AND received_method IS NOT NULL AND confirmed_at IS NOT NULL
      AND mismatch_flag=(finance_method<>received_method))
 )
);
CREATE INDEX IF NOT EXISTS advances_owner_date_idx ON public.advances(office_boy_id,created_at DESC);
CREATE INDEX IF NOT EXISTS advances_status_idx ON public.advances(status,created_at DESC);

CREATE TABLE IF NOT EXISTS public.expenses (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 flow_type text NOT NULL CHECK (flow_type IN ('float','reimbursement')),
 item_description text NOT NULL CHECK (length(trim(item_description)) BETWEEN 1 AND 500),
 amount numeric(12,2) NOT NULL CHECK (amount > 0 AND amount::text NOT IN ('NaN','Infinity','-Infinity')),
 reason text NOT NULL CHECK (length(trim(reason)) BETWEEN 1 AND 2000),
 bill_path text,
 status text NOT NULL DEFAULT 'Pending',
 payment_method_finance text CHECK (payment_method_finance IN ('Cash','Card')),
 payment_method_received text CHECK (payment_method_received IN ('Cash','Card')),
 mismatch_flag boolean NOT NULL DEFAULT false,
 rejection_reason text CHECK (length(trim(rejection_reason)) BETWEEN 1 AND 2000),
 rejection_acknowledged_at timestamptz,
 cleared_at timestamptz,
 paid_at timestamptz,
 reviewed_by uuid REFERENCES public.users(uid) ON DELETE RESTRICT,
 reviewed_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT expense_flow_status_valid CHECK (
  (flow_type='float' AND status IN ('Pending','Approved','Rejected','Rejection Acknowledged'))
  OR (flow_type='reimbursement' AND status IN ('Pending','Approved','Rejected','Rejection Acknowledged','Payment Cleared','Paid'))
 ),
 CONSTRAINT expense_payment_consistent CHECK (
  (flow_type='float' AND payment_method_finance IS NULL AND payment_method_received IS NULL
   AND cleared_at IS NULL AND paid_at IS NULL AND NOT mismatch_flag)
  OR (flow_type='reimbursement'
      AND (status NOT IN ('Payment Cleared','Paid') OR (payment_method_finance IS NOT NULL AND cleared_at IS NOT NULL))
      AND (status<>'Paid' OR (payment_method_received IS NOT NULL AND paid_at IS NOT NULL
       AND mismatch_flag=(payment_method_finance<>payment_method_received)))
      AND (status='Paid' OR (payment_method_received IS NULL AND paid_at IS NULL AND NOT mismatch_flag)))
 ),
 CONSTRAINT expense_rejection_consistent CHECK (
  (status IN ('Rejected','Rejection Acknowledged'))=(rejection_reason IS NOT NULL)
  AND (status='Rejection Acknowledged')=(rejection_acknowledged_at IS NOT NULL)
 )
);
CREATE INDEX IF NOT EXISTS expenses_owner_date_idx ON public.expenses(office_boy_id,created_at DESC);
CREATE INDEX IF NOT EXISTS expenses_queue_idx ON public.expenses(flow_type,status,created_at DESC);

-- Append-only movements. Available = credit - deduction - active holds.
-- A hold is released only after approval or the owner's rejection acknowledgement.
CREATE TABLE IF NOT EXISTS public.float_ledger (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 advance_id uuid REFERENCES public.advances(id) ON DELETE RESTRICT,
 expense_id uuid REFERENCES public.expenses(id) ON DELETE RESTRICT,
 entry_type text NOT NULL CHECK (entry_type IN ('credit','hold','hold_release','deduction')),
 amount numeric(12,2) NOT NULL CHECK (amount>0 AND amount::text NOT IN ('NaN','Infinity','-Infinity')),
 actor_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ledger_source_valid CHECK (
  (entry_type='credit' AND advance_id IS NOT NULL AND expense_id IS NULL)
  OR (entry_type<>'credit' AND advance_id IS NULL AND expense_id IS NOT NULL)
 ),
 UNIQUE(advance_id,entry_type), UNIQUE(expense_id,entry_type)
);
CREATE INDEX IF NOT EXISTS float_ledger_owner_date_idx ON public.float_ledger(office_boy_id,created_at DESC,id DESC);

CREATE TABLE IF NOT EXISTS public.payment_activity (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 advance_id uuid REFERENCES public.advances(id) ON DELETE RESTRICT,
 expense_id uuid REFERENCES public.expenses(id) ON DELETE RESTRICT,
 office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 actor_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
 action text NOT NULL,
 detail jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT activity_one_source CHECK ((advance_id IS NULL)<>(expense_id IS NULL))
);
CREATE INDEX IF NOT EXISTS payment_activity_advance_idx ON public.payment_activity(advance_id,created_at,id);
CREATE INDEX IF NOT EXISTS payment_activity_expense_idx ON public.payment_activity(expense_id,created_at,id);

ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS related_advance_id uuid REFERENCES public.advances(id) ON DELETE SET NULL;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS related_expense_id uuid REFERENCES public.expenses(id) ON DELETE SET NULL;

ALTER TABLE public.advances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.float_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_activity ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.advances,public.expenses,public.float_ledger,public.payment_activity FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.advances,public.expenses,public.float_ledger,public.payment_activity TO authenticated;
GRANT ALL ON public.advances,public.expenses,public.float_ledger,public.payment_activity TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.float_ledger_id_seq,public.payment_activity_id_seq TO service_role;
GRANT SELECT(related_advance_id,related_expense_id) ON public.notifications TO authenticated;

DROP POLICY IF EXISTS advances_read ON public.advances;
CREATE POLICY advances_read ON public.advances FOR SELECT TO authenticated USING (
 public.current_user_role() IS NOT NULL AND
 (office_boy_id=auth.uid() OR public.current_user_role() IN ('finance','admin','super_admin'))
);
DROP POLICY IF EXISTS expenses_read ON public.expenses;
CREATE POLICY expenses_read ON public.expenses FOR SELECT TO authenticated USING (
 public.current_user_role() IS NOT NULL AND
 (office_boy_id=auth.uid() OR public.current_user_role() IN ('finance','admin','super_admin'))
);
DROP POLICY IF EXISTS float_ledger_read ON public.float_ledger;
CREATE POLICY float_ledger_read ON public.float_ledger FOR SELECT TO authenticated USING (
 public.current_user_role() IS NOT NULL AND
 (office_boy_id=auth.uid() OR public.current_user_role() IN ('finance','admin','super_admin'))
);
DROP POLICY IF EXISTS payment_activity_read ON public.payment_activity;
CREATE POLICY payment_activity_read ON public.payment_activity FOR SELECT TO authenticated USING (
 public.current_user_role() IS NOT NULL AND
 (office_boy_id=auth.uid() OR public.current_user_role() IN ('finance','admin','super_admin'))
);

-- Uploaded bills must remain private and cannot be removed after submission.
DROP POLICY IF EXISTS receipts_delete ON storage.objects;
CREATE POLICY receipts_delete ON storage.objects FOR DELETE TO authenticated
 USING(bucket_id='receipts' AND public.current_user_role() IS NOT NULL AND owner=auth.uid()
  AND NOT EXISTS(SELECT 1 FROM public.requests WHERE "billImageUrl"=name)
  AND NOT EXISTS(SELECT 1 FROM public.expenses WHERE bill_path=name));

-- Financial history is immutable, including for privileged API clients.
CREATE OR REPLACE FUNCTION public.prevent_payment_history_change() RETURNS trigger
LANGUAGE plpgsql SET search_path=public AS $$
BEGIN RAISE EXCEPTION 'Payment history cannot be changed or deleted' USING ERRCODE='42501'; END $$;
DROP TRIGGER IF EXISTS float_ledger_immutable ON public.float_ledger;
CREATE TRIGGER float_ledger_immutable BEFORE UPDATE OR DELETE ON public.float_ledger
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_history_change();
DROP TRIGGER IF EXISTS payment_activity_immutable ON public.payment_activity;
CREATE TRIGGER payment_activity_immutable BEFORE UPDATE OR DELETE ON public.payment_activity
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_history_change();
REVOKE ALL ON FUNCTION public.prevent_payment_history_change() FROM PUBLIC,anon,authenticated;

DO $$ DECLARE t text; BEGIN
 IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
  FOREACH t IN ARRAY ARRAY['advances','expenses','float_ledger','payment_activity'] LOOP
   IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN
    EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
   END IF;
  END LOOP;
 END IF;
END $$;
COMMIT;
