BEGIN;

-- Preserve pre-existing rows as version 1 history. All new records use version 2.
ALTER TABLE public.advance_requests
  ADD COLUMN IF NOT EXISTS office_id uuid REFERENCES public.offices(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS amount_requested numeric(12,2),
  ADD COLUMN IF NOT EXISTS payment_method_requested text,
  ADD COLUMN IF NOT EXISTS receiver_account_name text,
  ADD COLUMN IF NOT EXISTS receiver_account_details text,
  ADD COLUMN IF NOT EXISTS cleared_by uuid REFERENCES public.users(uid) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS cleared_method text,
  ADD COLUMN IF NOT EXISTS cleared_at timestamptz,
  ADD COLUMN IF NOT EXISTS finance_note text,
  ADD COLUMN IF NOT EXISTS flow_version smallint NOT NULL DEFAULT 1;
UPDATE public.advance_requests a
SET office_id = u.office_id, amount_requested = a.amount
FROM public.users u WHERE u.uid = a.office_boy_id
  AND (a.office_id IS NULL OR a.amount_requested IS NULL);
ALTER TABLE public.advance_requests
  ALTER COLUMN office_id SET NOT NULL,
  ALTER COLUMN amount_requested SET NOT NULL;
ALTER TABLE public.advance_requests DROP CONSTRAINT IF EXISTS advance_requests_status_check;
ALTER TABLE public.advance_requests DROP CONSTRAINT IF EXISTS advance_request_decision_valid;
ALTER TABLE public.advance_requests DROP CONSTRAINT IF EXISTS advance_requests_v2_valid;
ALTER TABLE public.advance_requests
  ADD CONSTRAINT advance_requests_v2_valid CHECK (
    (flow_version = 1 AND status IN ('Pending','Approved','Rejected')) OR
    (flow_version = 2 AND status IN ('pending','cleared','fully_utilized')
      AND amount_requested = amount
      AND payment_method_requested IN ('cash','card')
      AND ((payment_method_requested = 'cash'
        AND receiver_account_name IS NULL AND receiver_account_details IS NULL)
        OR (payment_method_requested = 'card'
          AND length(trim(coalesce(receiver_account_name,''))) BETWEEN 1 AND 120
          AND length(trim(coalesce(receiver_account_details,''))) BETWEEN 1 AND 500))
      AND ((status = 'pending' AND cleared_by IS NULL AND cleared_method IS NULL AND cleared_at IS NULL)
        OR (status IN ('cleared','fully_utilized') AND cleared_by IS NOT NULL
          AND cleared_method = payment_method_requested AND cleared_at IS NOT NULL))
      AND length(coalesce(finance_note,'')) <= 2000)
  );
CREATE INDEX IF NOT EXISTS advance_requests_v2_office_status_idx
  ON public.advance_requests(office_id,status,created_at DESC) WHERE flow_version = 2;

CREATE TABLE IF NOT EXISTS public.advance_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  advance_request_id uuid NOT NULL REFERENCES public.advance_requests(id) ON DELETE RESTRICT,
  office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
  office_id uuid NOT NULL REFERENCES public.offices(id) ON DELETE RESTRICT,
  item_description text NOT NULL CHECK (length(trim(item_description)) BETWEEN 1 AND 500),
  amount_spent numeric(12,2) NOT NULL CHECK (amount_spent > 0 AND amount_spent < 10000000000),
  bill_path text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS advance_items_request_date_idx
  ON public.advance_items(advance_request_id,created_at DESC);

CREATE TABLE IF NOT EXISTS public.advance_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advance_request_id uuid NOT NULL REFERENCES public.advance_requests(id) ON DELETE RESTRICT,
  advance_item_id uuid UNIQUE REFERENCES public.advance_items(id) ON DELETE RESTRICT,
  office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
  office_id uuid NOT NULL REFERENCES public.offices(id) ON DELETE RESTRICT,
  entry_type text NOT NULL CHECK (entry_type IN ('credit','spend')),
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  actor_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT advance_ledger_source_valid CHECK (
    (entry_type = 'credit' AND advance_item_id IS NULL) OR
    (entry_type = 'spend' AND advance_item_id IS NOT NULL)
  )
);
CREATE UNIQUE INDEX IF NOT EXISTS advance_ledger_one_credit_idx
  ON public.advance_ledger(advance_request_id) WHERE entry_type = 'credit';
CREATE INDEX IF NOT EXISTS advance_ledger_request_date_idx
  ON public.advance_ledger(advance_request_id,created_at DESC,id DESC);

CREATE TABLE IF NOT EXISTS public.reimbursement_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
  office_id uuid NOT NULL REFERENCES public.offices(id) ON DELETE RESTRICT,
  item_description text NOT NULL CHECK (length(trim(item_description)) BETWEEN 1 AND 500),
  amount_spent numeric(12,2) NOT NULL CHECK (amount_spent > 0 AND amount_spent < 10000000000),
  bill_path text,
  payment_method_wanted text NOT NULL CHECK (payment_method_wanted IN ('cash','card')),
  receiver_account_name text CHECK (length(receiver_account_name) <= 120),
  receiver_account_details text CHECK (length(receiver_account_details) <= 500),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','paid')),
  rejection_reason text CHECK (length(trim(rejection_reason)) BETWEEN 1 AND 2000),
  reviewed_by uuid REFERENCES public.users(uid) ON DELETE RESTRICT,
  reviewed_at timestamptz,
  paid_method text CHECK (paid_method IN ('cash','card')),
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reimbursement_state_valid CHECK (
    (status = 'pending' AND reviewed_by IS NULL AND reviewed_at IS NULL
      AND rejection_reason IS NULL AND paid_method IS NULL AND paid_at IS NULL) OR
    (status = 'approved' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL
      AND rejection_reason IS NULL AND paid_method IS NULL AND paid_at IS NULL) OR
    (status = 'rejected' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL
      AND rejection_reason IS NOT NULL AND paid_method IS NULL AND paid_at IS NULL) OR
    (status = 'paid' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL
      AND rejection_reason IS NULL AND paid_method IS NOT NULL AND paid_at IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS reimbursements_office_status_idx
  ON public.reimbursement_requests(office_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS reimbursements_owner_date_idx
  ON public.reimbursement_requests(office_boy_id,created_at DESC);

CREATE TABLE IF NOT EXISTS public.core_payment_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advance_request_id uuid REFERENCES public.advance_requests(id) ON DELETE RESTRICT,
  reimbursement_id uuid REFERENCES public.reimbursement_requests(id) ON DELETE RESTRICT,
  office_boy_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
  office_id uuid NOT NULL REFERENCES public.offices(id) ON DELETE RESTRICT,
  actor_id uuid NOT NULL REFERENCES public.users(uid) ON DELETE RESTRICT,
  action text NOT NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT core_activity_one_source CHECK ((advance_request_id IS NULL) <> (reimbursement_id IS NULL))
);
CREATE INDEX IF NOT EXISTS core_activity_advance_idx ON public.core_payment_activity(advance_request_id,created_at,id);
CREATE INDEX IF NOT EXISTS core_activity_reimbursement_idx ON public.core_payment_activity(reimbursement_id,created_at,id);

ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS related_core_advance_id uuid REFERENCES public.advance_requests(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS related_reimbursement_id uuid REFERENCES public.reimbursement_requests(id) ON DELETE SET NULL;
GRANT SELECT(related_core_advance_id,related_reimbursement_id) ON public.notifications TO authenticated;

ALTER TABLE public.advance_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advance_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reimbursement_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.core_payment_activity ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.advance_items,public.advance_ledger,public.reimbursement_requests,
  public.core_payment_activity FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.advance_items,public.advance_ledger,public.reimbursement_requests,
  public.core_payment_activity TO authenticated;
GRANT ALL ON public.advance_items,public.advance_ledger,public.reimbursement_requests,
  public.core_payment_activity TO service_role;

DROP POLICY IF EXISTS advance_requests_read ON public.advance_requests;
CREATE POLICY advance_requests_read ON public.advance_requests FOR SELECT TO authenticated USING (
  public.current_user_role() IN ('finance','admin','super_admin') OR
  (office_boy_id = auth.uid() AND office_id = public.current_office_id())
);
DROP POLICY IF EXISTS advance_items_read ON public.advance_items;
CREATE POLICY advance_items_read ON public.advance_items FOR SELECT TO authenticated USING (
  public.current_user_role() IN ('finance','admin','super_admin') OR
  (office_boy_id = auth.uid() AND office_id = public.current_office_id())
);
DROP POLICY IF EXISTS advance_ledger_read ON public.advance_ledger;
CREATE POLICY advance_ledger_read ON public.advance_ledger FOR SELECT TO authenticated USING (
  public.current_user_role() IN ('finance','admin','super_admin') OR
  (office_boy_id = auth.uid() AND office_id = public.current_office_id())
);
DROP POLICY IF EXISTS reimbursements_read ON public.reimbursement_requests;
CREATE POLICY reimbursements_read ON public.reimbursement_requests FOR SELECT TO authenticated USING (
  public.current_user_role() IN ('finance','admin','super_admin') OR
  (office_boy_id = auth.uid() AND office_id = public.current_office_id())
);
DROP POLICY IF EXISTS core_activity_read ON public.core_payment_activity;
CREATE POLICY core_activity_read ON public.core_payment_activity FOR SELECT TO authenticated USING (
  public.current_user_role() IN ('finance','admin','super_admin') OR
  (office_boy_id = auth.uid() AND office_id = public.current_office_id())
);

-- Bills and the money trail cannot be edited after submission.
DROP TRIGGER IF EXISTS advance_items_immutable ON public.advance_items;
CREATE TRIGGER advance_items_immutable BEFORE UPDATE OR DELETE ON public.advance_items
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_history_change();
DROP TRIGGER IF EXISTS advance_ledger_immutable ON public.advance_ledger;
CREATE TRIGGER advance_ledger_immutable BEFORE UPDATE OR DELETE ON public.advance_ledger
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_history_change();
DROP TRIGGER IF EXISTS core_activity_immutable ON public.core_payment_activity;
CREATE TRIGGER core_activity_immutable BEFORE UPDATE OR DELETE ON public.core_payment_activity
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_history_change();
DROP POLICY IF EXISTS receipts_delete ON storage.objects;
CREATE POLICY receipts_delete ON storage.objects FOR DELETE TO authenticated USING (
  bucket_id='receipts' AND public.current_user_role() IS NOT NULL AND owner=auth.uid()
  AND NOT EXISTS(SELECT 1 FROM public.requests WHERE "billImageUrl"=name)
  AND NOT EXISTS(SELECT 1 FROM public.expenses WHERE bill_path=name)
  AND NOT EXISTS(SELECT 1 FROM public.advance_items WHERE bill_path=name)
  AND NOT EXISTS(SELECT 1 FROM public.reimbursement_requests WHERE bill_path=name)
);

CREATE OR REPLACE FUNCTION public.core_advance_balance(p_request_id uuid) RETURNS numeric
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT coalesce(sum(CASE entry_type WHEN 'credit' THEN amount ELSE -amount END),0)
  FROM public.advance_ledger WHERE advance_request_id = p_request_id
$$;
REVOKE ALL ON FUNCTION public.core_advance_balance(uuid) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.request_advance_v2(
  p_id uuid,p_purpose text,p_amount numeric,p_method text,
  p_account_name text DEFAULT NULL,p_account_details text DEFAULT NULL
) RETURNS public.advance_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE actor public.users; result public.advance_requests;
BEGIN
  SELECT * INTO actor FROM public.users WHERE uid = auth.uid() AND "isActive";
  IF actor.role IS DISTINCT FROM 'office_boy' THEN RAISE EXCEPTION 'Only an Office Boy can request an advance' USING ERRCODE='42501'; END IF;
  IF p_id IS NULL OR NOT public.payment_amount_valid(p_amount)
    OR length(trim(coalesce(p_purpose,''))) NOT BETWEEN 1 AND 2000
    OR p_method IS NULL OR p_method NOT IN ('cash','card')
    OR (p_method='card' AND (length(trim(coalesce(p_account_name,''))) NOT BETWEEN 1 AND 120
      OR length(trim(coalesce(p_account_details,''))) NOT BETWEEN 1 AND 500))
    OR (p_method='cash' AND (nullif(trim(coalesce(p_account_name,'')),'') IS NOT NULL
      OR nullif(trim(coalesce(p_account_details,'')),'') IS NOT NULL))
  THEN RAISE EXCEPTION 'Check the amount, purpose and payment details'; END IF;
  SELECT * INTO result FROM public.advance_requests WHERE id = p_id;
  IF FOUND THEN
    IF result.flow_version <> 2 OR result.office_boy_id <> actor.uid OR result.amount_requested <> p_amount
      OR result.purpose <> trim(p_purpose) OR result.payment_method_requested <> p_method
      OR result.receiver_account_name IS DISTINCT FROM nullif(trim(p_account_name),'')
      OR result.receiver_account_details IS DISTINCT FROM nullif(trim(p_account_details),'')
    THEN RAISE EXCEPTION 'Request reference already used'; END IF;
    RETURN result;
  END IF;
  INSERT INTO public.advance_requests(id,office_boy_id,office_id,amount,amount_requested,purpose,status,
    payment_method_requested,receiver_account_name,receiver_account_details,flow_version)
  VALUES(p_id,actor.uid,actor.office_id,p_amount,p_amount,trim(p_purpose),'pending',p_method,
    nullif(trim(p_account_name),''),nullif(trim(p_account_details),''),2)
  RETURNING * INTO result;
  INSERT INTO public.core_payment_activity(advance_request_id,office_boy_id,office_id,actor_id,action)
  VALUES(result.id,actor.uid,actor.office_id,actor.uid,'requested');
  INSERT INTO public.notifications(user_id,title,message,related_core_advance_id)
  SELECT uid,'Advance requested',actor.name||' requested PKR '||p_amount||'.',result.id
  FROM public.users WHERE "isActive" AND role='finance';
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.clear_advance_request_v2(p_id uuid,p_method text,p_note text DEFAULT NULL)
RETURNS public.advance_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE actor public.users; result public.advance_requests;
BEGIN
  SELECT * INTO actor FROM public.users WHERE uid=auth.uid() AND "isActive";
  IF actor.role IS DISTINCT FROM 'finance' THEN RAISE EXCEPTION 'Only Finance can clear advances' USING ERRCODE='42501'; END IF;
  SELECT * INTO result FROM public.advance_requests WHERE id=p_id FOR UPDATE;
  IF NOT FOUND OR result.flow_version<>2 THEN RAISE EXCEPTION 'Advance request not found'; END IF;
  IF result.status<>'pending' THEN RAISE EXCEPTION 'This advance is no longer waiting'; END IF;
  IF p_method IS DISTINCT FROM result.payment_method_requested OR length(coalesce(p_note,''))>2000 THEN
    RAISE EXCEPTION 'Use the requested Cash or Card method'; END IF;
  UPDATE public.advance_requests SET status='cleared',cleared_by=actor.uid,cleared_method=p_method,
    cleared_at=now(),finance_note=nullif(trim(p_note),'') WHERE id=p_id RETURNING * INTO result;
  INSERT INTO public.advance_ledger(advance_request_id,office_boy_id,office_id,entry_type,amount,actor_id)
  VALUES(result.id,result.office_boy_id,result.office_id,'credit',result.amount_requested,actor.uid);
  INSERT INTO public.core_payment_activity(advance_request_id,office_boy_id,office_id,actor_id,action,
    detail) VALUES(result.id,result.office_boy_id,result.office_id,actor.uid,'cleared',
    jsonb_build_object('method',p_method));
  INSERT INTO public.notifications(user_id,title,message,related_core_advance_id)
  VALUES(result.office_boy_id,'Advance sent','Finance marked your advance as sent.',result.id);
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.log_advance_item_v2(
  p_id uuid,p_advance_id uuid,p_item text,p_amount numeric,p_bill_path text DEFAULT NULL
) RETURNS public.advance_items LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE actor public.users; advance public.advance_requests; result public.advance_items; balance numeric;
BEGIN
  SELECT * INTO actor FROM public.users WHERE uid=auth.uid() AND "isActive";
  IF actor.role IS DISTINCT FROM 'office_boy' THEN RAISE EXCEPTION 'Only an Office Boy can add advance items' USING ERRCODE='42501'; END IF;
  IF p_id IS NULL OR NOT public.payment_amount_valid(p_amount)
    OR length(trim(coalesce(p_item,''))) NOT BETWEEN 1 AND 500
    OR (p_bill_path IS NOT NULL AND (p_bill_path NOT LIKE actor.uid::text||'/%' OR p_bill_path LIKE '%..%'))
  THEN RAISE EXCEPTION 'Check the item and amount'; END IF;
  SELECT * INTO result FROM public.advance_items WHERE id=p_id;
  IF FOUND THEN
    IF result.office_boy_id<>actor.uid OR result.advance_request_id<>p_advance_id
      OR result.item_description<>trim(p_item) OR result.amount_spent<>p_amount
      OR result.bill_path IS DISTINCT FROM p_bill_path THEN RAISE EXCEPTION 'Item reference already used'; END IF;
    RETURN result;
  END IF;
  SELECT * INTO advance FROM public.advance_requests WHERE id=p_advance_id FOR UPDATE;
  IF NOT FOUND OR advance.flow_version<>2 OR advance.office_boy_id<>actor.uid
    OR advance.office_id<>actor.office_id THEN RAISE EXCEPTION 'Advance not found' USING ERRCODE='42501'; END IF;
  IF advance.status<>'cleared' THEN RAISE EXCEPTION 'This advance is not available for spending'; END IF;
  balance:=public.core_advance_balance(p_advance_id);
  IF p_amount>balance THEN RAISE EXCEPTION 'This exceeds your remaining advance balance'; END IF;
  INSERT INTO public.advance_items(id,advance_request_id,office_boy_id,office_id,item_description,amount_spent,bill_path)
  VALUES(p_id,p_advance_id,actor.uid,actor.office_id,trim(p_item),p_amount,p_bill_path) RETURNING * INTO result;
  INSERT INTO public.advance_ledger(advance_request_id,advance_item_id,office_boy_id,office_id,entry_type,amount,actor_id)
  VALUES(p_advance_id,result.id,actor.uid,actor.office_id,'spend',p_amount,actor.uid);
  IF balance=p_amount THEN UPDATE public.advance_requests SET status='fully_utilized' WHERE id=p_advance_id; END IF;
  INSERT INTO public.core_payment_activity(advance_request_id,office_boy_id,office_id,actor_id,action,detail)
  VALUES(p_advance_id,actor.uid,actor.office_id,actor.uid,'item_added',
    jsonb_build_object('item_id',result.id,'amount',p_amount,'item',result.item_description));
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.advance_balances_v2()
RETURNS TABLE(advance_request_id uuid,office_boy_id uuid,office_id uuid,total numeric,spent numeric,remaining numeric,item_count bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE role_name text;
BEGIN
  role_name:=public.current_user_role();
  IF role_name IS NULL THEN RAISE EXCEPTION 'Not authorized' USING ERRCODE='42501'; END IF;
  RETURN QUERY SELECT a.id,a.office_boy_id,a.office_id,a.amount_requested,
    coalesce(sum(i.amount_spent),0),public.core_advance_balance(a.id),count(i.id)
  FROM public.advance_requests a LEFT JOIN public.advance_items i ON i.advance_request_id=a.id
  WHERE a.flow_version=2 AND a.status IN ('cleared','fully_utilized')
    AND (role_name IN ('finance','admin','super_admin')
      OR (a.office_boy_id=auth.uid() AND a.office_id=public.current_office_id()))
  GROUP BY a.id,a.office_boy_id,a.office_id,a.amount_requested,a.created_at
  ORDER BY a.created_at DESC;
END $$;

CREATE OR REPLACE FUNCTION public.submit_reimbursement_v2(
  p_id uuid,p_item text,p_amount numeric,p_method text,p_bill_path text DEFAULT NULL,
  p_account_name text DEFAULT NULL,p_account_details text DEFAULT NULL
) RETURNS public.reimbursement_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE actor public.users; result public.reimbursement_requests;
BEGIN
  SELECT * INTO actor FROM public.users WHERE uid=auth.uid() AND "isActive";
  IF actor.role IS DISTINCT FROM 'office_boy' THEN RAISE EXCEPTION 'Only an Office Boy can request repayment' USING ERRCODE='42501'; END IF;
  IF p_id IS NULL OR NOT public.payment_amount_valid(p_amount)
    OR length(trim(coalesce(p_item,''))) NOT BETWEEN 1 AND 500
    OR p_method IS NULL OR p_method NOT IN ('cash','card')
    OR length(coalesce(p_account_name,''))>120 OR length(coalesce(p_account_details,''))>500
    OR (p_method='cash' AND (nullif(trim(coalesce(p_account_name,'')),'') IS NOT NULL
      OR nullif(trim(coalesce(p_account_details,'')),'') IS NOT NULL))
    OR (p_bill_path IS NOT NULL AND (p_bill_path NOT LIKE actor.uid::text||'/%' OR p_bill_path LIKE '%..%'))
  THEN RAISE EXCEPTION 'Check the item, amount and payment details'; END IF;
  SELECT * INTO result FROM public.reimbursement_requests WHERE id=p_id;
  IF FOUND THEN
    IF result.office_boy_id<>actor.uid OR result.item_description<>trim(p_item)
      OR result.amount_spent<>p_amount OR result.payment_method_wanted<>p_method
      OR result.bill_path IS DISTINCT FROM p_bill_path
      OR result.receiver_account_name IS DISTINCT FROM nullif(trim(p_account_name),'')
      OR result.receiver_account_details IS DISTINCT FROM nullif(trim(p_account_details),'')
    THEN RAISE EXCEPTION 'Request reference already used'; END IF;
    RETURN result;
  END IF;
  INSERT INTO public.reimbursement_requests(id,office_boy_id,office_id,item_description,amount_spent,bill_path,
    payment_method_wanted,receiver_account_name,receiver_account_details)
  VALUES(p_id,actor.uid,actor.office_id,trim(p_item),p_amount,p_bill_path,p_method,
    nullif(trim(p_account_name),''),nullif(trim(p_account_details),'')) RETURNING * INTO result;
  INSERT INTO public.core_payment_activity(reimbursement_id,office_boy_id,office_id,actor_id,action)
  VALUES(result.id,actor.uid,actor.office_id,actor.uid,'requested');
  INSERT INTO public.notifications(user_id,title,message,related_reimbursement_id)
  SELECT uid,'Repayment requested',actor.name||' requested PKR '||p_amount||' repayment.',result.id
  FROM public.users WHERE "isActive" AND role='finance';
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.review_reimbursement_v2(p_id uuid,p_decision text,p_reason text DEFAULT NULL)
RETURNS public.reimbursement_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE actor public.users; result public.reimbursement_requests;
BEGIN
  SELECT * INTO actor FROM public.users WHERE uid=auth.uid() AND "isActive";
  IF actor.role IS DISTINCT FROM 'finance' THEN RAISE EXCEPTION 'Only Finance can review repayments' USING ERRCODE='42501'; END IF;
  IF p_decision IS NULL OR p_decision NOT IN ('approve','reject') OR (p_decision='reject'
    AND length(trim(coalesce(p_reason,''))) NOT BETWEEN 1 AND 2000) THEN RAISE EXCEPTION 'Add a reason when rejecting'; END IF;
  SELECT * INTO result FROM public.reimbursement_requests WHERE id=p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Repayment request not found'; END IF;
  IF result.status<>'pending' THEN RAISE EXCEPTION 'This request has already been reviewed'; END IF;
  UPDATE public.reimbursement_requests SET status=CASE WHEN p_decision='approve' THEN 'approved' ELSE 'rejected' END,
    rejection_reason=CASE WHEN p_decision='reject' THEN trim(p_reason) END,
    reviewed_by=actor.uid,reviewed_at=now(),updated_at=now() WHERE id=p_id RETURNING * INTO result;
  INSERT INTO public.core_payment_activity(reimbursement_id,office_boy_id,office_id,actor_id,action,detail)
  VALUES(result.id,result.office_boy_id,result.office_id,actor.uid,p_decision,
    jsonb_build_object('reason',result.rejection_reason));
  INSERT INTO public.notifications(user_id,title,message,related_reimbursement_id)
  VALUES(result.office_boy_id,CASE WHEN p_decision='approve' THEN 'Repayment approved' ELSE 'Repayment rejected' END,
    CASE WHEN p_decision='approve' THEN 'Finance approved your repayment request.'
      ELSE 'Finance rejected your request: '||result.rejection_reason END,result.id);
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.mark_reimbursement_paid_v2(p_id uuid,p_method text)
RETURNS public.reimbursement_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE actor public.users; result public.reimbursement_requests;
BEGIN
  SELECT * INTO actor FROM public.users WHERE uid=auth.uid() AND "isActive";
  IF actor.role IS DISTINCT FROM 'finance' THEN RAISE EXCEPTION 'Only Finance can mark repayments paid' USING ERRCODE='42501'; END IF;
  IF p_method IS NULL OR p_method NOT IN ('cash','card') THEN RAISE EXCEPTION 'Choose Cash or Card'; END IF;
  SELECT * INTO result FROM public.reimbursement_requests WHERE id=p_id FOR UPDATE;
  IF NOT FOUND OR result.status<>'approved' THEN RAISE EXCEPTION 'Only approved requests can be marked paid'; END IF;
  UPDATE public.reimbursement_requests SET status='paid',paid_method=p_method,paid_at=now(),updated_at=now()
  WHERE id=p_id RETURNING * INTO result;
  INSERT INTO public.core_payment_activity(reimbursement_id,office_boy_id,office_id,actor_id,action,detail)
  VALUES(result.id,result.office_boy_id,result.office_id,actor.uid,'paid',jsonb_build_object('method',p_method));
  INSERT INTO public.notifications(user_id,title,message,related_reimbursement_id)
  VALUES(result.office_boy_id,'Repayment paid','Finance marked your repayment as paid.',result.id);
  RETURN result;
END $$;

-- Old client releases must not offer unsolicited advances or replaced payment transitions.
DO $$ DECLARE signature regprocedure; BEGIN
  FOR signature IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
  WHERE n.nspname='public' AND p.proname IN
    ('give_advance','confirm_advance','submit_payment_expense','review_payment_expense',
     'acknowledge_payment_rejection','clear_reimbursement_payment','confirm_reimbursement_payment',
     'request_advance','review_advance_request','submit_request','review_request',
     'settle_advance_request','verify_advance_settlement')
  LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated',signature); END LOOP;
END $$;
REVOKE ALL ON FUNCTION public.request_advance_v2(uuid,text,numeric,text,text,text),
  public.clear_advance_request_v2(uuid,text,text),
  public.log_advance_item_v2(uuid,uuid,text,numeric,text),
  public.advance_balances_v2(),
  public.submit_reimbursement_v2(uuid,text,numeric,text,text,text,text),
  public.review_reimbursement_v2(uuid,text,text),
  public.mark_reimbursement_paid_v2(uuid,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.request_advance_v2(uuid,text,numeric,text,text,text),
  public.clear_advance_request_v2(uuid,text,text),
  public.log_advance_item_v2(uuid,uuid,text,numeric,text),
  public.advance_balances_v2(),
  public.submit_reimbursement_v2(uuid,text,numeric,text,text,text,text),
  public.review_reimbursement_v2(uuid,text,text),
  public.mark_reimbursement_paid_v2(uuid,text) TO authenticated;

DO $$ DECLARE t text; BEGIN
  IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
    FOREACH t IN ARRAY ARRAY['advance_items','advance_ledger','reimbursement_requests','core_payment_activity'] LOOP
      IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime'
        AND schemaname='public' AND tablename=t) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
      END IF;
    END LOOP;
  END IF;
END $$;
NOTIFY pgrst, 'reload schema';
COMMIT;
